apiVersion: v1
kind: Service
metadata:
  name: pingapp
  labels:
    app: pingapp
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
    - port: 4567
      protocol: TCP
      targetPort: 4567
  selector:
    app: pingapp